# Generated by Django 3.0.6 on 2020-05-24 10:54

from django.db import migrations, models
import django.db.models.deletion


def filData(apps, schema_editor):

    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Car = apps.get_model("fleet", "Car")
    Car.objects.bulk_create([
        Car(brand="VOLVO", year=2012, petrol=2, model="XC60"),
        Car(brand="Suzuki", year=2002, petrol=1, model="Swift"),

    ])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='Brand', max_length=12)),
                ('petrol', models.IntegerField(choices=[(1, 'LPG'), (2, 'DIESEL'), (3, 'ELECTRIC'), (4, 'HYBRID')], default=1)),
                ('model', models.CharField(max_length=32)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('car_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fleet.Car')),
                ('load', models.IntegerField()),
            ],
            bases=('fleet.car',),
        ),
        migrations.RunPython(filData),

    ]
